### ISSUE TITLE
[Request] implement color compression

### ISSUE THREAD

**Issue by DeflateAwning** [TheRealOrange/icer_compression#7]
Just leaving this here as an open request. Would love to use this on a real-life space or space-like mission in the future, but would need support for color imagery. 

I'm curious if the way to implement this is just performing the B&W compression on each color channel independently, or if there is a proposed way to implement sharing of data between color channels?

**Comment by ephemeridis** [comment]
I have chosen to use YCbCr compression. The weightage for the Cb and Cr channels can be changed for lossy compression to prioritise the Y channel.

**Comment by DeflateAwning** [comment]
Very neat, thank you!
